spring:
  application:
    name: auth-service
  cloud:
    aws:
      region:
        static: us-east-1
      credentials:
        access-key: test
        secret-key: test
      secretsmanager:
        endpoint: http://localstack:4566
  config:
    import:
      - "aws-secretsmanager:prod/keycloak/auth"
      - "optional:configserver:http://config-service:8888"
    fall-fast: true

    retry:
      initial-interval: 3000
      max-attempts: 10
      multiplier: 1.5

logging:
  level:
    org.springframework.boot.context.config: DEBUG